services:
    node:
        image: node:22
        command: ["sh", "-c", "npm install && npm start"]
        volumes:
            - .:/app
        working_dir: /app
        environment:
            NODE_ENV: development
        ports:
            - "3000:3000"
